Maintenance.

diff --git a/mccore/configure b/mccore/configure
--- a/mccore/configure
+++ b/mccore/configure
@@ -2785,6 +2785,78 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_have_fstreambase" >&5
 echo "${ECHO_T}$ac_cv_have_fstreambase" >&6
 
+
+echo "$as_me:$LINENO: checking whether the compiler has numeric_limits<T>" >&5
+echo $ECHO_N "checking whether the compiler has numeric_limits<T>... $ECHO_C" >&6
+if test "${ac_cv_cxx_have_numeric_limits+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <limits>
+ using namespace std;
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+double e = numeric_limits<double>::epsilon(); return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_cxx_have_numeric_limits=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_cxx_have_numeric_limits=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_cxx_have_numeric_limits" >&5
+echo "${ECHO_T}$ac_cv_cxx_have_numeric_limits" >&6
+if test "$ac_cv_cxx_have_numeric_limits" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_NUMERIC_LIMITS
+_ACEOF
+
+fi
+
+
 if eval "test -z \"`echo $GXX`\""; then # not gnu compiler
     case "$host" in
     *-sgi-*)
@@ -2813,8 +2885,8 @@ if eval "test -z \"`echo $GXX`\""; then # not gnu compiler
         LINKOPTIONS= ;;
     esac;
 elif eval "test \"`echo $GXX`\" = yes"; then     # gnu compiler
-	CXXSHFLAGS=" ";
-	CXXFLAGS="";
+	CXXSHFLAGS=" -fmessage-length=0";
+	CXXFLAGS=" -fmessage-length=0";
 	DEPFLAGS="-MM -Wno-deprecated"
 	LDFLAGS="-static $LDFLAGS"
 	LINKOPTIONS=;
@@ -2835,8 +2907,8 @@ fi;
 # Check whether --with-optimization or --without-optimization was given.
 if test "${with_optimization+set}" = set; then
   withval="$with_optimization"
-  CXXFLAGS="-O2 $CXXFLAGS";
-CXXSHFLAGS="-O2 $CXXSHFLAGS";
+  CXXFLAGS="-O2 $CXXFLAGS -pg";
+CXXSHFLAGS="-O2 $CXXSHFLAGS -pg";
 
 fi;
 
